## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'greateyes'

package-url = 'https://github.com/Attolab/pymodaq_plugins_greateyes'
description = 'some word about your plugin'

author = 'PyMoDAQ plugin for instruments from Greateyes (ALEX, ELSE, GE XXXX)'
author-email = 'romain.geneaux@cea.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = []
